name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite:3.35.0
        options: >-
          --blobHost 0.0.0.0
          --blobPort 10000
          --queueHost 0.0.0.0
          --queuePort 10001
          --tableHost 0.0.0.0
          --tablePort 10002
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
        volumes:
          - azurite-data:/data
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 27.2
            elixir: 1.18.1
            coverage: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v6

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Wait for Azurite to be ready
        run: |
          until curl -f http://localhost:10000/devstoreaccount1; do
            echo "Waiting for Azurite..."
            sleep 2
          done

      - name: Run tests
        run: mix test --trace
